### ISSUE TITLE
Fully Change name throughout the project

### ISSUE THREAD

**Issue by BelfordZ** [etclabscore/evm-rs#1]
As the title suggests

 - [ ] code
 - [ ] docs

**Comment by mersinvald** [comment]
Unresolved questions:
 - Feasibility of renaming
 - What's the new name? `evm` is too generic and virtually unsearchable.

**Comment by mersinvald** [comment]
Kamino cloned this issue to [ethereumproject/evm-rs](https://github.com/ethereumproject/evm-rs/issues/19)
