### ISSUE TITLE
Setup Jenkins

### ISSUE THREAD

**Issue by mersinvald** [etclabscore/evm-rs#21]
@BelfordZ please add evm-rs to jenkins.etclabs.org.

TODO: write a Jenkins file to run internal evm tests

Start Date: TODO
Expected Duration: 1-3 days

**Comment by BelfordZ** [comment]
it is enabled, you just have to add a jenkinsfile.

**Comment by mersinvald** [comment]
Kamino cloned this issue to [ethereumproject/evm-rs](https://github.com/ethereumproject/evm-rs/issues/21)
